<a href="https://colab.research.google.com/github/hagalaz-star/PROJECT/blob/main/AI_06_%EC%B5%9C%EC%9B%90%EC%A4%80_CS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

aisles = pd.read_csv('/content/drive/MyDrive/project/aisles.csv')
departments = pd.read_csv('/content/drive/MyDrive/project/departments.csv')
order_products_prior = pd.read_csv('/content/drive/MyDrive/project/order_products__prior.csv')
order_products_train = pd.read_csv('/content/drive/MyDrive/project/order_products__train.csv')
orders = pd.read_csv('/content/drive/MyDrive/project/orders.csv')
products= pd.read_csv('/content/drive/MyDrive/project/products.csv')

orders: This table includes all orders, namely prior, train, and test.(orders_id)

order_products_train: This table includes training orders.(order_id and product_id) and indicates whether a product in an order is a reorder or not (through the reordered variable).

order_products_prior : This table includes prior orders. It has a composite primary key (order_id and product_id) and indicates whether a product in an order is a reorder or not (through the reordered variable).

products: This table includes all products.(product_id)

aisles: This table includes all aisles. (aisle_id)

departments: This table includes all departments.(department_id)

In [ ]:
print(aisles.isnull().sum())
aisles

aisle_id    0
aisle       0
dtype: int64


aisle_id                       aisle
0           1       prepared soups salads
1           2           specialty cheeses
2           3         energy granola bars
3           4               instant foods
4           5  marinades meat preparation
..        ...                         ...
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

[134 rows x 2 columns]

In [ ]:
print(departments.isnull().sum())
departments

department_id    0
department       0
dtype: int64


department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

In [ ]:
print(order_products_prior.isnull().sum())
order_products_prior

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64


order_id  product_id  add_to_cart_order  reordered
0                2       33120                  1          1
1                2       28985                  2          1
2                2        9327                  3          0
3                2       45918                  4          1
4                2       30035                  5          0
...            ...         ...                ...        ...
32434484   3421083       39678                  6          1
32434485   3421083       11352                  7          0
32434486   3421083        4600                  8          0
32434487   3421083       24852                  9          1
32434488   3421083        5020                 10          1

[32434489 rows x 4 columns]

In [ ]:
print(order_products_train.isnull().sum())
order_products_train

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64


order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]

In [ ]:
print(orders.isnull().sum())
orders

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64


order_id  user_id  ... order_hour_of_day  days_since_prior_order
0         2539329        1  ...                 8                     NaN
1         2398795        1  ...                 7                    15.0
2          473747        1  ...                12                    21.0
3         2254736        1  ...                 7                    29.0
4          431534        1  ...                15                    28.0
...           ...      ...  ...               ...                     ...
3421078   2266710   206209  ...                18                    29.0
3421079   1854736   206209  ...                10                    30.0
3421080    626363   206209  ...                12                    18.0
3421081   2977660   206209  ...                12                     7.0
3421082    272231   206209  ...                14                    30.0

[3421083 rows x 7 columns]

In [ ]:
print(products.isnull().sum())
products

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64


product_id  ... department_id
0               1  ...            19
1               2  ...            13
2               3  ...             7
3               4  ...             1
4               5  ...            13
...           ...  ...           ...
49683       49684  ...             5
49684       49685  ...             1
49685       49686  ...             3
49686       49687  ...             8
49687       49688  ...            11

[49688 rows x 4 columns]

# 데이터 전처리

In [ ]:
# 결측치 처리('days_since_prior_order':첫 구매인경우 nan값이 입력되어 있음 => 0으로 대체)
#orders['days_since_prior_order'] = orders['days_since_prior_order'].fillna(0)
orders = orders.dropna()

In [ ]:
print(orders.shape)
orders['eval_set'].value_counts()

(3214874, 7)


prior    3008665
train     131209
test       75000
Name: eval_set, dtype: int64

In [ ]:
orders[(orders['user_id']==10)]

order_id  user_id  ... order_hour_of_day  days_since_prior_order
84     68288       10  ...                15                    30.0
85   2115522       10  ...                19                    12.0
86     83395       10  ...                15                    14.0
87   1353310       10  ...                20                    23.0
88   1822501       10  ...                19                    30.0

[5 rows x 7 columns]

In [ ]:
orders[orders['user_id'].isin(orders['user_id'][orders['eval_set']=='test'])]

order_id  user_id  ... order_hour_of_day  days_since_prior_order
27         444309        3  ...                19                     9.0
28        3002854        3  ...                16                    21.0
29        2037211        3  ...                18                    20.0
30        2710558        3  ...                17                    12.0
31        1972919        3  ...                16                     7.0
...           ...      ...  ...               ...                     ...
3421064   3059777   206208  ...                10                    13.0
3421065   2239861   206208  ...                 4                     9.0
3421066   1285346   206208  ...                11                     5.0
3421067   1882108   206208  ...                22                     7.0
3421068    803273   206208  ...                11                     4.0

[1167497 rows x 7 columns]

In [ ]:
orders['user_id'].value_counts()

53684     99
201623    99
50817     99
176951    99
88911     99
          ..
24224      3
199509     3
32420      3
21310      3
196830     3
Name: user_id, Length: 206209, dtype: int64

In [ ]:
import random
random.seed(2021)

# 1만명의 유저만 샘플링 (첫시도)
user = random.sample(orders['user_id'][orders['eval_set']=='train'].unique().tolist(), 10000)
#user = orders['user_id'][orders['eval_set']=='train'].unique().tolist() #샘플링 안하고 시도 (실패)
# orders에서 test dataset 관련 기록(prior포함) 제외
orders_2 = orders[orders['user_id'].isin(user)]

In [ ]:
print("유저 인원:",len(user), "// 주문건수 합:",len(orders_2))

유저 인원: 10000 // 주문건수 합: 155579


In [ ]:
order_products_prior = order_products_prior[order_products_prior['order_id'].isin(orders_2['order_id'])]

# 데이터 합치기

In [ ]:
# 제품 정보 : product + aisles + department data
product_m = products.merge(aisles).merge(departments)
product_m

product_id  ... department
0               1  ...     snacks
1              78  ...     snacks
2             102  ...     snacks
3             172  ...     snacks
4             285  ...     snacks
...           ...  ...        ...
49683       22827  ...       bulk
49684       28655  ...       bulk
49685       30365  ...       bulk
49686       38007  ...       bulk
49687       48778  ...       bulk

[49688 rows x 6 columns]

In [ ]:
# product one-hot encoding data 
product_enc = pd.get_dummies(product_m, columns=['aisle'], prefix=[None])
product_enc

product_id  ... yogurt
0               1  ...      0
1              78  ...      0
2             102  ...      0
3             172  ...      0
4             285  ...      0
...           ...  ...    ...
49683       22827  ...      0
49684       28655  ...      0
49685       30365  ...      0
49686       38007  ...      0
49687       48778  ...      0

[49688 rows x 139 columns]

In [ ]:
order_product = pd.concat([order_products_prior,order_products_train]) 
order_product

order_id  product_id  add_to_cart_order  reordered
56              6       40462                  1          0
57              6       15873                  2          0
58              6       41897                  3          0
566            69       43875                  1          1
567            69       27845                  2          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[2844704 rows x 4 columns]

In [ ]:
# 주문 항목 정보 : product_m + order_product
order_detail = order_product.merge(product_m,how='left') #.sample(n=100000, random_state=2021)

In [ ]:
order_detail#.sort_values(by=order_detail['order_id'])

order_id  product_id  ...                          aisle  department
0               6       40462  ...                   refrigerated   beverages
1               6       15873  ...                        laundry   household
2               6       41897  ...         air fresheners candles   household
3              69       43875  ...              baby food formula      babies
4              69       27845  ...                           milk  dairy eggs
...           ...         ...  ...                            ...         ...
2844699   3421063       14233  ...  water seltzer sparkling water   beverages
2844700   3421063       35548  ...                 prepared meals        deli
2844701   3421070       35951  ...                soy lactosefree  dairy eggs
2844702   3421070       16953  ...                        spreads      pantry
2844703   3421070        4724  ...               packaged produce     produce

[2844704 rows x 9 columns]

In [ ]:
data = orders_2.merge(order_detail)#, on ='order_id')

In [ ]:
data

order_id  user_id  ...              aisle       department
0         3166874       48  ...   fresh vegetables          produce
1         3166874       48  ...                tea        beverages
2         3166874       48  ...        fresh herbs          produce
3         3166874       48  ...   fresh vegetables          produce
4         3166874       48  ...       fresh fruits          produce
...           ...      ...  ...                ...              ...
1566105   2048154   206185  ...          dry pasta  dry goods pasta
1566106   2048154   206185  ...        pasta sauce  dry goods pasta
1566107   2048154   206185  ...  baby food formula           babies
1566108   2048154   206185  ...  baby food formula           babies
1566109   2048154   206185  ...  baby food formula           babies

[1566110 rows x 15 columns]

In [ ]:
data.isnull().sum()

order_id                  0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
product_id                0
add_to_cart_order         0
reordered                 0
product_name              0
aisle_id                  0
department_id             0
aisle                     0
department                0
dtype: int64

# 유튜브 추천 알고리즘 

In [ ]:
import zipfile
import pandas as pd
import numpy as np
import random

In [ ]:
data['user_id'] = data['user_id'].astype(int)
data['product_id'] = data['product_id'].astype(int)
data['order_id'] = data['order_id'].astype(int)
data['days_since_prior_order'] = data['days_since_prior_order'].astype(int)

data = data.set_index(['user_id']).sort_index()
data = data.reset_index()

In [ ]:
# 유저 인덱스 인코딩
user_ids = data["user_id"].unique().tolist()
user2user_encoded = {x: i for i, x in enumerate(user_ids)}
#userencoded2user = {i: x for i, x in enumerate(user_ids)}

# 주문 인덱스 인코딩
order_ids = data["order_id"].unique().tolist()
order2order_encoded = {x: i for i, x in enumerate(order_ids)}
#order_encoded2order = {i: x for i, x in enumerate(order_ids)}

# 상품 인덱스 인코딩
product_ids = data["product_id"].unique().tolist()
product2product_encoded = {x: i for i, x in enumerate(product_ids)}
#product_encoded2product = {i: x for i, x in enumerate(product_ids)}

# 상품 이름 인코딩
pd_name_ids = data["product_name"].unique().tolist()
pd_name2pd_name_encoded = {x: i for i, x in enumerate(pd_name_ids)}
#pd_name_encoded2pd_name = {i: x for i, x in enumerate(pd_name_ids)}

# 상품 대분류 인덱스 인코딩
department_ids = data["department_id"].unique().tolist()
department2department_encoded = {x: i for i, x in enumerate(department_ids)}
#department_encoded2department = {i: x for i, x in enumerate(department_ids)}

# 상품 소분류 인덱스 인코딩
aisle_ids = data["aisle_id"].unique().tolist()
aisle2aisle_encoded = {x: i for i, x in enumerate(aisle_ids)}
#aisle_encoded2aisle = {i: x for i, x in enumerate(aisle_ids)}

# 상품 대분류명 인덱스 인코딩
dept_name_ids = data["department"].unique().tolist()
dept_name2dept_name_encoded = {x: i for i, x in enumerate(dept_name_ids)}
#dept_name_encoded2dept_name = {i: x for i, x in enumerate(dept_name_ids)}

# 상품 소분류명 인덱스 인코딩
aisle_name_ids = data["aisle"].unique().tolist()
aisle_name2aisle_name_encoded = {x: i for i, x in enumerate(aisle_name_ids)}
#aisle_name_encoded2aisle_name = {i: x for i, x in enumerate(aisle_name_ids)}

In [ ]:
# 인코딩으로 바꾸기
data["user"] = data["user_id"].map(user2user_encoded)
data["product"] = data["product_id"].map(product2product_encoded)
data["order"] = data["order_id"].map(order2order_encoded)
data["pd_name"] = data["product_name"].map(pd_name2pd_name_encoded)

User기준으로 데이터 조정(feature engineering)

'구매자 기준으로 데이터프레임 재생성

In [ ]:
order_hist = data.groupby(['user'])['order_id'].unique().apply(list).reset_index()
product_hist = data.groupby(['user'])['product_id'].apply(list).reset_index()# unique().적용해보기
order_dow_hist = data.groupby(['user'])['order_dow'].apply(list).reset_index() 
order_hour_of_day_hist = data.groupby(['user'])['order_hour_of_day'].apply(list).reset_index()
days_since_prior_order_hist = data.groupby(['user'])['days_since_prior_order'].apply(list).reset_index()

In [ ]:
data.groupby(['user'])['product_id'].apply(list)

user
0       [45007, 22613, 28842, 21405, 26209, 19508, 248...
1       [12341, 6184, 10441, 46149, 196, 14309, 46149,...
2       [49075, 39121, 21724, 48017, 36695, 28289, 391...
3       [34213, 34574, 7029, 25305, 41950, 31338, 4235...
4       [2186, 42699, 25753, 46496, 42139, 24157, 2415...
                              ...                        
9995    [20512, 18918, 17948, 24489, 13176, 19057, 817...
9996    [12099, 40706, 43129, 48119, 8523, 7192, 35761...
9997    [24852, 24710, 27307, 32642, 20919, 12508, 267...
9998    [23650, 26165, 11087, 48775, 36305, 47977, 428...
9999    [30217, 35473, 25915, 14852, 15829, 24613, 399...
Name: product_id, Length: 10000, dtype: object

In [ ]:
data.groupby(['user'])['order_dow'].unique().apply(list)

user
0                      [5, 6]
1             [1, 2, 3, 5, 4]
2             [4, 6, 0, 1, 2]
3       [0, 4, 1, 6, 2, 5, 3]
4                [4, 5, 2, 1]
                ...          
9995    [0, 2, 3, 5, 1, 6, 4]
9996       [2, 4, 3, 1, 5, 6]
9997                [0, 6, 5]
9998    [0, 1, 2, 4, 6, 3, 5]
9999          [3, 2, 1, 5, 4]
Name: order_dow, Length: 10000, dtype: object

In [ ]:
order_product_hist = data.groupby(['order'])['product_id'].apply(list).reset_index()

In [ ]:
order_hist # 사용자의 주문목록

user                                           order_id
0        0  [3166874, 2766710, 501067, 1643524, 1657641, 7...
1        1  [1318871, 1261384, 2100631, 580568, 1680554, 2...
2        2  [964058, 2163945, 3349827, 1376443, 2655621, 1...
3        3  [2568280, 1763414, 3092533, 414538, 1538989, 3...
4        4  [251784, 3211781, 1469604, 1515062, 1342998, 2...
...    ...                                                ...
9995  9995  [1911923, 549547, 3130715, 2582484, 1258873, 2...
9996  9996  [992039, 2551929, 1053779, 2760916, 1877978, 1...
9997  9997          [2822394, 83431, 56199, 1597643, 1782820]
9998  9998  [3115357, 1209728, 164466, 3304125, 1983173, 1...
9999  9999  [2275747, 1597200, 497488, 1874713, 1286942, 1...

[10000 rows x 2 columns]

In [ ]:
# 최다(빈도) 구매자의 주문 수(heavy user)

max([x for x in order_hist['order_id'].apply(len)])

99

In [ ]:
product_hist  # 사용자가 구매한 상품 

user                                         product_id
0        0  [45007, 22613, 28842, 21405, 26209, 19508, 248...
1        1  [12341, 6184, 10441, 46149, 196, 14309, 46149,...
2        2  [49075, 39121, 21724, 48017, 36695, 28289, 391...
3        3  [34213, 34574, 7029, 25305, 41950, 31338, 4235...
4        4  [2186, 42699, 25753, 46496, 42139, 24157, 2415...
...    ...                                                ...
9995  9995  [20512, 18918, 17948, 24489, 13176, 19057, 817...
9996  9996  [12099, 40706, 43129, 48119, 8523, 7192, 35761...
9997  9997  [24852, 24710, 27307, 32642, 20919, 12508, 267...
9998  9998  [23650, 26165, 11087, 48775, 36305, 47977, 428...
9999  9999  [30217, 35473, 25915, 14852, 15829, 24613, 399...

[10000 rows x 2 columns]

In [ ]:
order_product_hist

order                                         product_id
0            0  [45007, 22613, 28842, 21405, 26209, 19508, 248...
1            1  [45007, 36695, 21405, 20339, 24830, 26209, 182...
2            2  [45007, 20339, 26209, 43662, 28842, 8057, 4399...
3            3  [47823, 20339, 4455, 26298, 17284, 4855, 45007...
4            4  [43662, 35855, 5621, 33000, 34012, 24940, 4455...
...        ...                                                ...
155574  155574                [49273, 34134, 35206, 35473, 10673]
155575  155575  [6052, 1716, 49296, 31268, 41673, 48337, 47167...
155576  155576                   [4978, 24613, 1716, 6052, 49296]
155577  155577  [27966, 49273, 49296, 35206, 48337, 7658, 4015...
155578  155578  [9088, 24291, 40153, 24835, 28427, 20191, 2409...

[155579 rows x 2 columns]

In [ ]:
# 주문 당 가장 많은 제품을 구입한 경우

max([x for x in order_product_hist['product_id'].apply(len)])

145

In [ ]:
order_dow_hist

user                                          order_dow
0        0  [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, ...
1        1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
2        2  [4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
3        3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, ...
4        4  [4, 4, 4, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...
...    ...                                                ...
9995  9995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
9996  9996  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, ...
9997  9997  [0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, ...
9998  9998  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...
9999  9999  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...

[10000 rows x 2 columns]

In [ ]:
order_hour_of_day_hist

user                                  order_hour_of_day
0        0  [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 1...
1        1  [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...
2        2  [10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 1...
3        3  [9, 9, 9, 9, 9, 9, 9, 9, 9, 14, 14, 14, 14, 14...
4        4  [14, 14, 14, 14, 14, 14, 18, 18, 18, 18, 18, 1...
...    ...                                                ...
9995  9995  [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 1...
9996  9996  [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 1...
9997  9997  [19, 19, 19, 19, 19, 19, 19, 19, 21, 21, 21, 2...
9998  9998  [14, 14, 14, 14, 14, 14, 14, 14, 14, 9, 9, 9, ...
9999  9999  [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, ...

[10000 rows x 2 columns]

In [ ]:
days_since_prior_order_hist

user                             days_since_prior_order
0        0  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
1        1  [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, ...
2        2  [10, 10, 10, 10, 10, 10, 30, 30, 30, 30, 30, 3...
3        3  [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 1...
4        4  [8, 8, 8, 30, 30, 30, 20, 20, 20, 20, 20, 20, ...
...    ...                                                ...
9995  9995  [22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 2...
9996  9996  [19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 1...
9997  9997  [18, 18, 18, 18, 18, 18, 18, 18, 30, 30, 30, 3...
9998  9998  [28, 28, 28, 28, 28, 28, 28, 28, 28, 30, 30, 3...
9999  9999  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...

[10000 rows x 2 columns]

In [ ]:
# User dataset 생성 (학습에 사용할 데이터, prior order:[data['eval_set']=='prior'])
user_data = data[['user','user_id']].merge(order_hist, how='left').merge(product_hist, how='left').merge(order_dow_hist, how='left').merge(order_hour_of_day_hist, how = 'left').merge(days_since_prior_order_hist,how='left') #eval_set
user_data

user  ...                             days_since_prior_order
0           0  ...  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
1           0  ...  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
2           0  ...  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
3           0  ...  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
4           0  ...  [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
...       ...  ...                                                ...
1566105  9999  ...  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...
1566106  9999  ...  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...
1566107  9999  ...  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...
1566108  9999  ...  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...
1566109  9999  ...  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 3...

[1566110 rows x 7 columns]

In [ ]:
user_data = user_data.drop_duplicates('user') # 중복데이터 삭제
user_data.shape

(10000, 7)

In [ ]:
data_product_prior=data['product'][data['eval_set']=='prior']

# predict_labels

In [ ]:
user_data['predict_labels'] = user_data['product_id'].apply(lambda x: int(random.uniform(0,data['product_id'].max())))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
user_data

user  ...  predict_labels
0           0  ...           28640
124         1  ...           47853
298         2  ...           48619
393         3  ...           26678
895         4  ...           19366
...       ...  ...             ...
1564717  9995  ...           36353
1565137  9996  ...           29010
1565463  9997  ...           37642
1565511  9998  ...           11406
1566023  9999  ...           41117

[10000 rows x 8 columns]

In [ ]:
train_data = user_data[(user_data.user>=30) &
                       (user_data.user<=39)]
test_data = user_data[(user_data.user>=40) &
                      (user_data.user<=59)]

# 모델 학습 및 추출

In [ ]:
data["product_id"].max()

49687

In [ ]:
data["product"].max()

35053

In [ ]:
# 하이퍼파라미터 정의

EMBEDDING_DIMS = 16
DENSE_UNITS = 64
DROPOUT_PCT = 0.1
ALPHA = 0.1
NUM_CLASSES = data["product_id"].max() + 2 
LEARNING_RATE = 0.1

In [ ]:
# custom layers

import tensorflow as tf
class MaskedEmbeddingsAggregatorLayer(tf.keras.layers.Layer):
    def __init__(self, agg_mode='sum', **kwargs):
        super(MaskedEmbeddingsAggregatorLayer, self).__init__(**kwargs)

        if agg_mode not in ['sum', 'mean']:
            raise NotImplementedError('mode {} not implemented!'.format(agg_mode))
        self.agg_mode = agg_mode
    
    @tf.function
    def call(self, inputs, mask=None):
        masked_embeddings = tf.ragged.boolean_mask(inputs, mask)
        if self.agg_mode == 'sum':
            aggregated =  tf.reduce_sum(masked_embeddings, axis=1)
        elif self.agg_mode == 'mean':
            aggregated = tf.reduce_mean(masked_embeddings, axis=1)
        return aggregated
    
    def get_config(self):
        # this is used when loading a saved model that uses a custom layer
        return {'agg_mode': self.agg_mode}
    
class L2NormLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(L2NormLayer, self).__init__(**kwargs)
    
    @tf.function
    def call(self, inputs, mask=None):
        if mask is not None:
            inputs = tf.ragged.boolean_mask(inputs, mask).to_tensor()
        return tf.math.l2_normalize(inputs, axis=-1)

    def compute_mask(self, inputs, mask):
        return mask

In [ ]:
import tensorflow as tf
import datetime
import os


input_user = tf.keras.Input(shape=(None, ), name='user') 
input_product_hist = tf.keras.layers.Input(shape=(None,), name='product_hist')
input_order_dow_hist = tf.keras.layers.Input(shape=(None,), name='order_dow_hist')
input_order_hour_of_day_hist = tf.keras.Input(shape=(None, ), name='order_hour_of_day_hist')
input_days_since_prior_order_hist = tf.keras.Input(shape=(None, ), name='days_since_prior_order_hist')


# layer 구성
features_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='features_embeddings')
labels_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='labels_embeddings')

avg_embeddings = MaskedEmbeddingsAggregatorLayer(agg_mode='mean', name='aggregate_embeddings')

dense_1 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_1')
dense_2 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_2')
dense_3 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_3')
l2_norm_1 = L2NormLayer(name='l2_norm_1')

dense_output = tf.keras.layers.Dense(NUM_CLASSES, activation=tf.nn.softmax, name='dense_output')

#--- features
features_embeddings = features_embedding_layer(input_user)
l2_norm_features = l2_norm_1(features_embeddings)
avg_features = avg_embeddings(l2_norm_features)

labels_product_embeddings = labels_embedding_layer(input_product_hist)
l2_norm_product = l2_norm_1(labels_product_embeddings)
avg_product = avg_embeddings(l2_norm_product)

labels_order_dow_embeddings = labels_embedding_layer(input_order_dow_hist)
l2_norm_order_dow = l2_norm_1(labels_order_dow_embeddings)
avg_order_dow = avg_embeddings(l2_norm_order_dow)

labels_order_hour_embeddings = labels_embedding_layer(input_order_hour_of_day_hist)
l2_norm_order_hour = l2_norm_1(labels_order_hour_embeddings)
avg_order_hour = avg_embeddings(l2_norm_order_hour)

labels_since_prior_embeddings = labels_embedding_layer(input_days_since_prior_order_hist)
l2_norm_since_prior = l2_norm_1(labels_since_prior_embeddings)
avg_since_prior = avg_embeddings(l2_norm_since_prior)


print(avg_features)
print(avg_order_dow)
print(avg_order_hour)
print(avg_since_prior)

# 임베딩 벡터들 연결
concat_inputs = tf.keras.layers.Concatenate(axis=1)([avg_product,
                                                     avg_order_dow, 
                                                     avg_order_hour,
                                                     avg_since_prior
                                                     ])
# Dense Layers
dense_1_features = dense_1(concat_inputs)
dense_1_relu = tf.keras.layers.ReLU(name='dense_1_relu')(dense_1_features)
dense_1_batch_norm = tf.keras.layers.BatchNormalization(name='dense_1_batch_norm')(dense_1_relu)

dense_2_features = dense_2(dense_1_relu)
dense_2_relu = tf.keras.layers.ReLU(name='dense_2_relu')(dense_2_features)
dense_2_batch_norm = tf.keras.layers.BatchNormalization(name='dense_2_batch_norm')(dense_2_relu)

dense_3_features = dense_3(dense_2_relu)
dense_3_relu = tf.keras.layers.ReLU(name='dense_3_relu')(dense_3_features)
dense_3_batch_norm = tf.keras.layers.BatchNormalization(name='dense_3_batch_norm')(dense_3_relu)

outputs = dense_output(dense_3_batch_norm)

#Optimizer
optimiser = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)

#--- prep model
model = tf.keras.models.Model(
    inputs=[input_product_hist,
            input_order_dow_hist,
            input_order_hour_of_day_hist,
            input_days_since_prior_order_hist
            ],
    outputs=[outputs]
)
logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics=['acc']) 

model.summary()


KerasTensor(type_spec=TensorSpec(shape=(None, 16), dtype=tf.float32, name=None), name='aggregate_embeddings/PartitionedCall:0', description="created by layer 'aggregate_embeddings'")
KerasTensor(type_spec=TensorSpec(shape=(None, 16), dtype=tf.float32, name=None), name='aggregate_embeddings/PartitionedCall:0', description="created by layer 'aggregate_embeddings'")
KerasTensor(type_spec=TensorSpec(shape=(None, 16), dtype=tf.float32, name=None), name='aggregate_embeddings/PartitionedCall:0', description="created by layer 'aggregate_embeddings'")
KerasTensor(type_spec=TensorSpec(shape=(None, 16), dtype=tf.float32, name=None), name='aggregate_embeddings/PartitionedCall:0', description="created by layer 'aggregate_embeddings'")
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 product_hist (InputLayer)      [(None, None)]       0 

In [ ]:
train_data

user  ...  predict_labels
5193    30  ...           28979
5482    31  ...           25251
5514    32  ...           12382
5565    33  ...           30245
5800    34  ...           38130
6108    35  ...           29049
6349    36  ...           39861
6412    37  ...            2747
6483    38  ...           31212
6502    39  ...           30464

[10 rows x 8 columns]

In [ ]:
# 학습(training)
history = model.fit([tf.keras.preprocessing.sequence.pad_sequences(train_data['product_id']),
                     tf.keras.preprocessing.sequence.pad_sequences(train_data['order_dow']),
                     tf.keras.preprocessing.sequence.pad_sequences(train_data['order_hour_of_day']), #+ 1e-10, dtype=float
                     tf.keras.preprocessing.sequence.pad_sequences(train_data['days_since_prior_order'])
                    ],train_data['predict_labels'].values,
                  #batch_size=16,
                  steps_per_epoch=1, epochs=300)

Epoch 1/300
1/1 [==============================] - 3s 3s/step - loss: 10.8130 - acc: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 24ms/step - loss: 10.6488 - acc: 0.0000e+00
Epoch 3/300
1/1 [==============================] - 0s 22ms/step - loss: 8.2690 - acc: 0.5000
Epoch 4/300
1/1 [==============================] - 0s 19ms/step - loss: 5.3295 - acc: 0.5000
Epoch 5/300
1/1 [==============================] - 0s 21ms/step - loss: 3.5099 - acc: 0.4000
Epoch 6/300
1/1 [==============================] - 0s 20ms/step - loss: 2.2784 - acc: 0.3000
Epoch 7/300
1/1 [==============================] - 0s 19ms/step - loss: 2.0316 - acc: 0.5000
Epoch 8/300
1/1 [==============================] - 0s 18ms/step - loss: 1.7906 - acc: 0.5000
Epoch 9/300
1/1 [==============================] - 0s 23ms/step - loss: 1.7965 - acc: 0.4000
Epoch 10/300
1/1 [==============================] - 0s 20ms/step - loss: 1.8304 - acc: 0.5000
Epoch 11/300
1/1 [==============================] - 0s 22ms/s

In [ ]:
# 모델 저장
model.save("candidate_generation.h5")

/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)


In [ ]:
# 모델 예측결과 추출
pred = model.predict([tf.keras.preprocessing.sequence.pad_sequences(test_data['product_id']),
           tf.keras.preprocessing.sequence.pad_sequences(test_data['order_dow']),
           tf.keras.preprocessing.sequence.pad_sequences(test_data['order_hour_of_day']), #+ 1e-10, dtype=float
           tf.keras.preprocessing.sequence.pad_sequences(test_data['days_since_prior_order'])
           ])

pred

array([[5.46481482e-09, 5.50375878e-09, 5.41793543e-09, ...,
        5.54110935e-09, 5.52526824e-09, 5.51290968e-09],
       [1.21191848e-08, 1.22682637e-08, 1.21664545e-08, ...,
        1.24673560e-08, 1.24832038e-08, 1.24150334e-08],
       [1.21191848e-08, 1.22682637e-08, 1.21664545e-08, ...,
        1.24673560e-08, 1.24832038e-08, 1.24150334e-08],
       ...,
       [1.21191848e-08, 1.22682637e-08, 1.21664545e-08, ...,
        1.24673560e-08, 1.24832038e-08, 1.24150334e-08],
       [1.21191848e-08, 1.22682637e-08, 1.21664545e-08, ...,
        1.24673560e-08, 1.24832038e-08, 1.24150334e-08],
       [1.21191848e-08, 1.22682637e-08, 1.21664545e-08, ...,
        1.24673560e-08, 1.24832038e-08, 1.24150334e-08]], dtype=float32)

In [ ]:
# candidate generation: 
###### 각 user당 top-7개의 추천 후보 데이터(predict_label)를 뽑아낸다.
import numpy as np
N = 7
k = np.sort((-pred).argsort()[:,:N])
print(k)
k = k.flatten()
k[k>data["product"].max()]=0
k = np.unique(k)

[[ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]
 [ 2747 12382 25251 29049 30464 31212 39861]]


In [ ]:
k

array([    0,  2747, 12382, 25251, 29049, 30464, 31212])

In [ ]:
# load candidate_generation 
model = tf.keras.models.load_model(
    'candidate_generation.h5',
    custom_objects={
        'L2NormLayer':L2NormLayer,
        'MaskedEmbeddingsAggregatorLayer':MaskedEmbeddingsAggregatorLayer
    }
)

In [ ]:
# 아이템의 속성(ex.aisle)을 불러오는 함수 

aisle_cols = aisles['aisle'].values.tolist()
# type(aisle_cols)
type(aisle_cols)
aisle_cols

aisles_encoded = {x: i for i, x in enumerate(aisle_cols)}


# movies-> product_enc
# genres-> aisles
# aisles -> ['a', 'b', 'c', ...]
def get_aisles(products, aisles):
	def get_all_aisles(ai):
		active = [str(aisles_encoded[aisle]) for aisle, a in zip(aisles, ai) if a==1]
		if len(active) == 0:
			return '0'
		return ','.join((active))
	
	products['all_aisles'] = [
                              get_all_aisles(ai) for ai in zip(*[products[aisle] for aisle in aisles]) # 문제없음.
                              ]

get_aisles(product_enc, aisle_cols)

In [ ]:
product_enc.head(1)

product_id                product_name  ...  yogurt  all_aisles
0           1  Chocolate Sandwich Cookies  ...       0          60

[1 rows x 140 columns]

In [ ]:
data['reordered'].value_counts()

1    981131
0    584979
Name: reordered, dtype: int64

In [ ]:
ratings = data[['product_id', 'reordered']]
ratings

product_id  reordered
0             45007          0
1             22613          0
2             28842          0
3             21405          0
4             26209          0
...             ...        ...
1566105       24097          0
1566106       14852          1
1566107       27061          0
1566108       19627          0
1566109        5192          0

[1566110 rows x 2 columns]

In [ ]:
# normalize
def normalize_col(df,col_name):
    df[col_name] = (df[col_name] - df[col_name].min()) / (df[col_name].max() - df[col_name].min())
    return df


In [ ]:
product_data = product_enc.set_index(['product_id']).sort_index()

# using candidate result 'k'
product_data = product_data.loc[k+1]
product_data["pd_name_d"] = product_data["product_name"].map(pd_name2pd_name_encoded)
print(product_data.head())

# 레퍼런스와 대조하여 feature 정리: 
 # rating -> reordered (1: like / 0: dislike)
 # unix_timestamp-> order_hour_of_day / 굳이 필요없으면 사용하지 않기. 
ratings_cols = ['user_id', 'product_id', 'reordered', 'order_hour_of_day']
ratings = data[['product_id', 'reordered', 'user_id', 'order_hour_of_day' ]]

# 모델에 사용할 new_data
new_data = product_data.merge(ratings, on='product_id') # rating 추가
print(new_data.columns)

aisle_occurences = new_data[aisle_cols].sum().to_dict()
aisles_encoded = {x: i for i, x in enumerate(aisle_cols)}

get_aisles(product_data, aisle_cols)

                                                 product_name  ...  pd_name_d
product_id                                                     ...           
1                                  Chocolate Sandwich Cookies  ...    12742.0
2748                         Organic Reduced Fat Omega-3 Milk  ...     1299.0
12383       Organic Elbows & Creamy Mild Cheddar Sauce Cre...  ...    11206.0
25252                              Vegan Veggie Salami Slices  ...        NaN
29050                                        Decorating Icing  ...        NaN

[5 rows x 140 columns]
Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'department',
       'air fresheners candles', 'asian foods', 'baby accessories',
       'baby bath body care', 'baby food formula',
       ...
       'trash bags liners', 'vitamins supplements',
       'water seltzer sparkling water', 'white wines', 'yogurt', 'all_aisles',
       'pd_name_d', 'reordered', 'user_id', 'order_hour_of_day'],
      dtype='object', l

In [ ]:
new_data.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'department',
       'air fresheners candles', 'asian foods', 'baby accessories',
       'baby bath body care', 'baby food formula',
       ...
       'trash bags liners', 'vitamins supplements',
       'water seltzer sparkling water', 'white wines', 'yogurt', 'all_aisles',
       'pd_name_d', 'reordered', 'user_id', 'order_hour_of_day'],
      dtype='object', length=144)

In [ ]:

new_data = new_data[['product_id', 'user_id', 'reordered', 'order_hour_of_day', 'all_aisles', 'pd_name_d']]
new_data['product_type'] = np.where(new_data['reordered'] ==1, 'like', 'dislike') # 1이면 like

product_list = new_data.groupby(['user_id','product_type'])['product_id'].apply(list).reset_index()

aisle_list = new_data.groupby(['user_id'])['all_aisles'].unique().apply(list).reset_index()
aisle_list['all_aisles']=aisle_list['all_aisles'].apply(lambda x: list(set(','.join(x))) ) # 중복제거
aisle_list['all_aisles']=aisle_list['all_aisles'].apply(lambda x:[ x for x in x if x.isdigit() ])
    
# normalize
new_data = normalize_col(new_data, 'order_hour_of_day')
order_hour_of_day_list = new_data.groupby(['user_id'])['order_hour_of_day'].unique().apply(list).reset_index()

pd_name_list = new_data.groupby(['user_id'])['pd_name_d'].apply(list).reset_index()
print(product_list)
dataset = product_list.pivot(index='user_id', columns='product_type', values='product_id').reset_index()
dataset.fillna(new_data["product_id"].max()+1, inplace=True)

dataset['like'] =dataset['like'].apply(lambda x: x if type(x) is list else [])
dataset['dislike'] =dataset['dislike'].apply(lambda x: x if type(x) is list else [])

dataset = pd.merge(dataset, pd_name_list, how='left')
dataset = pd.merge(dataset, aisle_list, how='left')
dataset = pd.merge(dataset, order_hour_of_day_list, how='left')


dataset['predict_labels'] = dataset['like'].apply(lambda x: int(random.uniform(1,new_data["product_id"].max()))) 

dataset['like']=dataset['like'].apply(lambda x: [new_data["product_id"].max()+1] if x == [] else x)
dataset['dislike']=dataset['dislike'].apply(lambda x: [new_data["product_id"].max()+1] if x == [] else x)
# train_data=dataset[(dataset.user_id >= 1)&
#                                   (dataset.user_id <= 5)]
# test_data=dataset[(dataset.user_id >= 6)&
#                                   (dataset.user_id <= 9)]
train_data_r=dataset[(dataset.index >= 0)&
                                  (dataset.index <= 9)]
test_data_r=dataset[(dataset.index >= 20)&
                                  (dataset.index <= 24)]

print(dataset.index)

     user_id product_type                                         product_id
0        409         like  [2748, 2748, 2748, 2748, 2748, 2748, 2748, 274...
1       6569      dislike                                             [2748]
2       6569         like                                       [2748, 2748]
3       9131      dislike                                             [2748]
4       9131         like                                             [2748]
..       ...          ...                                                ...
106   183794      dislike                                                [1]
107   186838      dislike                                             [2748]
108   188689      dislike                                                [1]
109   188689         like                                                [1]
110   199804      dislike                                             [2748]

[111 rows x 3 columns]
Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
train_data_r

user_id  ... predict_labels
0      409  ...          19367
1     6569  ...          24352
2     9131  ...          15210
3    12157  ...          24391
4    14135  ...           9805
5    15175  ...          12264
6    15989  ...           9851
7    20687  ...           5130
8    21285  ...          14200
9    22032  ...          21906

[10 rows x 7 columns]

In [ ]:
test_data_r

user_id  ... predict_labels
20    51506  ...          27960
21    52918  ...            557
22    53085  ...           3247
23    54496  ...           6453
24    54577  ...          27402

[5 rows x 7 columns]

In [ ]:
EMBEDDING_DIMS = 16
DENSE_UNITS = 64
DROPOUT_PCT = 0.1
ALPHA = 0.0
NUM_CLASSES=new_data["product_id"].max() + 3
LEARNING_RATE = 0.003

In [ ]:
#---inputs
import tensorflow as tf
import datetime
import os
input_name = tf.keras.Input(shape=(None, ), name='product_name')
inp_item_liked = tf.keras.layers.Input(shape=(None,), name='like')
inp_item_disliked = tf.keras.layers.Input(shape=(None,), name='dislike')
input_aisle = tf.keras.Input(shape=(None, ), name='aisle')
input_order_hour = tf.keras.Input(shape=(None, ), name='order_hour')


#--- layers
features_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='features_embeddings')
labels_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='labels_embeddings')

avg_embeddings = MaskedEmbeddingsAggregatorLayer(agg_mode='mean', name='aggregate_embeddings')

dense_1 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_1')
dense_2 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_2')
dense_3 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_3')
l2_norm_1 = L2NormLayer(name='l2_norm_1')

dense_output = tf.keras.layers.Dense(NUM_CLASSES, activation=tf.nn.softmax, name='dense_output')

#--- features
features_embeddings = features_embedding_layer(input_name)
l2_norm_features = l2_norm_1(features_embeddings)
avg_features = avg_embeddings(l2_norm_features)

labels_liked_embeddings = labels_embedding_layer(inp_item_liked)
l2_norm_liked = l2_norm_1(labels_liked_embeddings)
avg_liked = avg_embeddings(l2_norm_liked)

labels_disliked_embeddings = labels_embedding_layer(inp_item_disliked)
l2_norm_disliked = l2_norm_1(labels_disliked_embeddings)
avg_disliked = avg_embeddings(l2_norm_disliked)

labels_aisle_embeddings = labels_embedding_layer(input_aisle)
l2_norm_aisle = l2_norm_1(labels_aisle_embeddings)
avg_aisle = avg_embeddings(l2_norm_aisle)

labels_order_hour_embeddings = labels_embedding_layer(input_order_hour)
l2_norm_order_hour = l2_norm_1(labels_order_hour_embeddings)
avg_order_hour = avg_embeddings(l2_norm_order_hour)


# 임베딩 벡터들 연결
concat_inputs = tf.keras.layers.Concatenate(axis=1)([avg_features,
                                                     avg_liked,
                                                     avg_disliked,
                                                     avg_aisle,
                                                     avg_order_hour
                                                     ])
# Dense Layers
dense_1_features = dense_1(concat_inputs)
dense_1_relu = tf.keras.layers.ReLU(name='dense_1_relu')(dense_1_features)
dense_1_batch_norm = tf.keras.layers.BatchNormalization(name='dense_1_batch_norm')(dense_1_relu)

dense_2_features = dense_2(dense_1_relu)
dense_2_relu = tf.keras.layers.ReLU(name='dense_2_relu')(dense_2_features)
# dense_2_batch_norm = tf.keras.layers.BatchNormalization(name='dense_2_batch_norm')(dense_2_relu)

dense_3_features = dense_3(dense_2_relu)
dense_3_relu = tf.keras.layers.ReLU(name='dense_3_relu')(dense_3_features)
dense_3_batch_norm = tf.keras.layers.BatchNormalization(name='dense_3_batch_norm')(dense_3_relu)
outputs = dense_output(dense_3_batch_norm)

#Optimizer
optimiser = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)

#--- prep model
model = tf.keras.models.Model(
    inputs=[input_name, 
            inp_item_liked, 
            inp_item_disliked,
            input_aisle,
            input_order_hour,
            ],
    outputs=[outputs]
)
logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics=['acc'])

model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 product_name (InputLayer)      [(None, None)]       0           []                               
                                                                                                  
 like (InputLayer)              [(None, None)]       0           []                               
                                                                                                  
 dislike (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 aisle (InputLayer)             [(None, None)]       0           []                               
                                                                                            

In [ ]:
train_data_r.columns

Index(['user_id', 'dislike', 'like', 'pd_name_d', 'all_aisles',
       'order_hour_of_day', 'predict_labels'],
      dtype='object')

In [ ]:
ratings1 = model.fit([tf.keras.preprocessing.sequence.pad_sequences(train_data_r['pd_name_d'])+ 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(train_data_r['like'])+ 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(train_data_r['dislike'])+ 1e-10,
            tf.keras.preprocessing.sequence.pad_sequences(train_data_r['all_aisles'])+ 1e-10,
            tf.keras.preprocessing.sequence.pad_sequences(train_data_r['order_hour_of_day'], dtype=float) + 1e-10,
           ],train_data_r['predict_labels'].values,
           steps_per_epoch=1, epochs=300)


Epoch 1/300
1/1 [==============================] - 2s 2s/step - loss: 10.3715 - acc: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 16ms/step - loss: 10.2674 - acc: 0.2000
Epoch 3/300
1/1 [==============================] - 0s 16ms/step - loss: 10.1779 - acc: 0.4000
Epoch 4/300
1/1 [==============================] - 0s 16ms/step - loss: 10.0783 - acc: 0.5000
Epoch 5/300
1/1 [==============================] - 0s 19ms/step - loss: 9.9787 - acc: 0.5000
Epoch 6/300
1/1 [==============================] - 0s 17ms/step - loss: 9.8757 - acc: 0.6000
Epoch 7/300
1/1 [==============================] - 0s 17ms/step - loss: 9.7660 - acc: 0.6000
Epoch 8/300
1/1 [==============================] - 0s 15ms/step - loss: 9.6526 - acc: 0.6000
Epoch 9/300
1/1 [==============================] - 0s 16ms/step - loss: 9.5368 - acc: 0.6000
Epoch 10/300
1/1 [==============================] - 0s 18ms/step - loss: 9.4166 - acc: 0.6000
Epoch 11/300
1/1 [==============================] - 0s 20ms/ste

In [ ]:
# prediction 
pred_1 = model.predict([tf.keras.preprocessing.sequence.pad_sequences(test_data_r['pd_name_d'])+ 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(test_data_r['like'])+ 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(test_data_r['dislike'])+ 1e-10,
            tf.keras.preprocessing.sequence.pad_sequences(test_data_r['all_aisles'])+ 1e-10,
            tf.keras.preprocessing.sequence.pad_sequences(test_data_r['order_hour_of_day'], dtype=float) + 1e-10
           ])

pred_1

array([[1.7135791e-07, 1.5287178e-07, 1.6155796e-07, ..., 1.5836201e-07,
        1.5973363e-07, 1.5679760e-07],
       [1.9563665e-06, 1.9225802e-06, 1.9142667e-06, ..., 1.9030758e-06,
        1.8290954e-06, 1.8871353e-06],
       [5.3532608e-07, 5.2692712e-07, 5.3356314e-07, ..., 5.3555078e-07,
        5.2450355e-07, 5.3472962e-07],
       [4.3464388e-06, 4.2077140e-06, 4.1916014e-06, ..., 4.1247358e-06,
        4.1019798e-06, 4.1488483e-06],
       [1.9563681e-06, 1.9225818e-06, 1.9142683e-06, ..., 1.9030756e-06,
        1.8290968e-06, 1.8871369e-06]], dtype=float32)

In [ ]:
# ranking
###### 각 user당 top-7개의 추천 데이터를 뽑아낸다.
N = 7
# k = np.sort((-pred_1).argsort()[:,:N]) 
# np.argsort(): probability의 마이너스값을 작은 값부터 순서대로 데이터의 인덱스를 반환. ==> 즉, 양의값으로는 큰 값부터 반환한 셈.
# np.sort(): 인덱스 순으로 다시 정렬. 확률이 더 높은 것부터 보고싶으므로 레퍼런스에 있는 코드이지만 사용하지 않음. 
ranking_1 = (-pred_1).argsort()[:, :N]

ranking_1[ranking_1>new_data['product_id'].max()]=0 

print(ranking_1)

ranking_1_probability = np.sort(pred_1[:, :N])
print(ranking_1_probability)

[[19367 12264 24352  9805 21906 24391 15210]
 [21906 14200  9851  5130 19367 12264 24391]
 [19367 12264 21906 24391 14200  5130  9851]
 [24391 21906 19367 14200  5130  9851 12264]
 [21906 14200  9851  5130 19367 12264 24391]]
[[1.5022569e-07 1.5251588e-07 1.5287178e-07 1.6155796e-07 1.6374993e-07
  1.6414063e-07 1.7135791e-07]
 [1.9142667e-06 1.9184631e-06 1.9225802e-06 1.9535232e-06 1.9563665e-06
  1.9629019e-06 2.0297375e-06]
 [5.2692712e-07 5.3089883e-07 5.3136182e-07 5.3356314e-07 5.3532608e-07
  5.4237495e-07 5.6018609e-07]
 [4.0751111e-06 4.1760641e-06 4.1916014e-06 4.2077140e-06 4.3464388e-06
  4.3566602e-06 4.3753971e-06]
 [1.9142683e-06 1.9184627e-06 1.9225818e-06 1.9535248e-06 1.9563681e-06
  1.9629035e-06 2.0297373e-06]]
